#!/usr/bin/env node
/**
 * Setup .env.local from persistent Firebase config + E2E password.
 *
 * Run: node scripts/setup-env.mjs
 *
 * Firebase config is stored permanently in ~/.claude/projects/-home-antoine-Spothitch/.env.firebase
 * E2E password is stored permanently in ~/.claude/projects/-home-antoine-Spothitch/.env.e2e-password
 *
 * After a crash/reset, just run this script to restore .env.local instantly.
 * No need to re-enter anything (unless the password file was also deleted).
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import readline from 'readline'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const projectRoot = path.resolve(__dirname, '..')
const envLocalPath = path.join(projectRoot, '.env.local')

// Persistent storage dir (survives crashes)
const persistDir = path.join(
  process.env.HOME,
  '.claude/projects/-home-antoine-Spothitch'
)
const firebaseConfigPath = path.join(persistDir, '.env.firebase')
const passwordPath = path.join(persistDir, '.env.e2e-password')

function readFirebaseConfig() {
  if (!fs.existsSync(firebaseConfigPath)) {
    console.error(`\n❌ Firebase config not found at: ${firebaseConfigPath}`)
    console.error('   Run: firebase apps:sdkconfig web <APP_ID> --project spothitch')
    console.error('   Then save to the file above.')
    process.exit(1)
  }
  const content = fs.readFileSync(firebaseConfigPath, 'utf8')
  const vars = {}
  for (const line of content.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const [key, ...rest] = trimmed.split('=')
    vars[key.trim()] = rest.join('=').trim()
  }
  return vars
}

function readPassword() {
  if (fs.existsSync(passwordPath)) {
    return fs.readFileSync(passwordPath, 'utf8').trim()
  }
  return null
}

function savePassword(pw) {
  fs.writeFileSync(passwordPath, pw, { mode: 0o600 })
}

async function askPassword() {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout })
  return new Promise((resolve) => {
    rl.question('🔑 E2E_TEST_PASSWORD (mot de passe des comptes ci-*@spothitch.com): ', (answer) => {
      rl.close()
      resolve(answer.trim())
    })
  })
}

async function main() {
  console.log('🔧 Setup .env.local for SpotHitch\n')

  // 1. Read Firebase config
  const firebase = readFirebaseConfig()
  console.log(`✅ Firebase config loaded (project: ${firebase.VITE_FIREBASE_PROJECT_ID})`)

  // 2. Get E2E password
  let password = readPassword()
  if (password) {
    console.log('✅ E2E password loaded from persistent storage')
  } else {
    // Check if passed as argument
    password = process.argv[2]
    if (password) {
      savePassword(password)
      console.log('✅ E2E password saved to persistent storage')
    } else {
      // Interactive prompt
      password = await askPassword()
      if (!password) {
        console.error('❌ Password required. Usage: node scripts/setup-env.mjs <password>')
        process.exit(1)
      }
      savePassword(password)
      console.log('✅ E2E password saved to persistent storage')
    }
  }

  // 3. Write .env.local
  const lines = [
    '# Auto-generated by scripts/setup-env.mjs',
    '# DO NOT commit this file (already in .gitignore)',
    `# Generated: ${new Date().toISOString()}`,
    '',
    '# Firebase config (public, from firebase apps:sdkconfig)',
    ...Object.entries(firebase).map(([k, v]) => `${k}=${v}`),
    '',
    '# E2E test password (private)',
    `E2E_TEST_PASSWORD=${password}`,
    '',
    '# Sentry (optional)',
    'VITE_SENTRY_DSN=',
    '',
    '# Beta flag',
    'VITE_SHOW_BETA=true',
    '',
  ]

  fs.writeFileSync(envLocalPath, lines.join('\n'))
  console.log(`\n✅ .env.local written to: ${envLocalPath}`)
  console.log('\n📋 Contenu:')
  for (const [k, v] of Object.entries(firebase)) {
    console.log(`   ${k}=${v.substring(0, 20)}...`)
  }
  console.log(`   E2E_TEST_PASSWORD=${'*'.repeat(password.length)}`)
  console.log('\n🚀 Ready! Run: npm run build && npx playwright test')
}

main()
